[package]
name = "trident-template"
version = "0.0.1"
edition = "2021"
repository = "https://github.com/Ackee-Blockchain/trident"
license-file = "../../LICENSE"
readme = "../../README.md"
description = "The trident template crate is dedicated to generated Trident fuzz test templates."
[dependencies]

# Trident IDL spec
trident-idl-spec = "0.0.1"

# Misc
syn = { version = "2", features = ["visit", "full"] }
quote = "1"
convert_case = "0.6"
sha2 = "0.10.0"
