[package]
name = "program_client"
version = "0.1.0"
edition = "2018"
[dependencies.trident-client]
path = "../../../../crates/client"

[dependencies.turnstile]
path = "../programs/turnstile"
features = ["no-entrypoint"]
