[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
maze0 = "HLUXYVSNW3unyAvuJW3C2MRH48X6vuiSAYzAE2sAm2L3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
