[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
cpi_metaplex_7 = "3XtULmXDGS867VbBXiPkjYr4EMjytGW8X12F6BS23Zcw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


# include metadata program in genesis
[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "trident-genesis/metaplex-token-metadata.so"
