//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;
use trident_fuzz::AccountDiscriminator;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: additional_program
// ----------------------------------------------------------------------------
pub mod additional_program {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for additional_program
    pub fn program_id() -> Pubkey {
        pubkey!("fill corresponding program ID here")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: Initialize
    // ....................................................................

    /// Main instruction struct for Initialize
    pub struct InitializeInstruction {
        pub accounts: InitializeInstructionAccountMetas,
        pub data: InitializeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Initialize instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeInstructionAccountMetas {}

    /// Account pubkeys for Initialize instruction
    #[derive(Debug, Clone)]
    pub struct InitializeInstructionAccounts {}

    impl InitializeInstructionAccounts {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Instruction data for Initialize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeInstructionData {}

    impl InitializeInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for InitializeInstruction
    impl InitializeInstruction {
        fn discriminator() -> [u8; 8] {
            [175u8, 175u8, 109u8, 31u8, 13u8, 152u8, 155u8, 237u8]
        }

        pub fn data(data: InitializeInstructionData) -> Self {
            Self {
                accounts: InitializeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeInstructionAccounts) -> Self {
            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Data Accounts (with discriminators)
    // ------------------------------------------------------------------------

    // ------------------------------------------------------------------------
    // Errors
    // ------------------------------------------------------------------------

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------

    // ------------------------------------------------------------------------
    // Custom Types
    // ------------------------------------------------------------------------
}

// ----------------------------------------------------------------------------
// Program: idl_test
// ----------------------------------------------------------------------------
pub mod idl_test {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for idl_test
    pub fn program_id() -> Pubkey {
        pubkey!("fill corresponding program ID here")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: ProcessRustTypes
    // ....................................................................

    /// Main instruction struct for ProcessRustTypes
    pub struct ProcessRustTypesInstruction {
        pub accounts: ProcessRustTypesInstructionAccountMetas,
        pub data: ProcessRustTypesInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ProcessRustTypes instruction
    #[derive(Debug, Clone, Default)]
    pub struct ProcessRustTypesInstructionAccountMetas {
        pub compositeAccountNested: CompositeAccountNestedInstructionAccountMetas,

        pub signer: AccountMeta,

        pub dataAccount1: AccountMeta,

        pub dataAccount2: AccountMeta,

        pub dataAccount3: AccountMeta,

        pub dataAccount4: AccountMeta,

        pub dataAccount5: AccountMeta,

        pub dataAccount6: AccountMeta,

        pub compositeAccount: CompositeAccountInstructionAccountMetas,
    }

    /// Account pubkeys for ProcessRustTypes instruction
    #[derive(Debug, Clone)]
    pub struct ProcessRustTypesInstructionAccounts {
        pub compositeAccountNested: CompositeAccountNestedInstructionAccounts,

        pub signer: Pubkey,

        pub dataAccount1: Pubkey,

        pub dataAccount2: Pubkey,

        pub dataAccount3: Pubkey,

        pub dataAccount4: Pubkey,

        pub dataAccount5: Pubkey,

        pub dataAccount6: Pubkey,

        pub compositeAccount: CompositeAccountInstructionAccounts,
    }

    impl ProcessRustTypesInstructionAccounts {
        pub fn new(
            compositeAccountNested: CompositeAccountNestedInstructionAccounts,

            signer: Pubkey,

            dataAccount1: Pubkey,

            dataAccount2: Pubkey,

            dataAccount3: Pubkey,

            dataAccount4: Pubkey,

            dataAccount5: Pubkey,

            dataAccount6: Pubkey,

            compositeAccount: CompositeAccountInstructionAccounts,
        ) -> Self {
            Self {
                compositeAccountNested,

                signer,

                dataAccount1,

                dataAccount2,

                dataAccount3,

                dataAccount4,

                dataAccount5,

                dataAccount6,

                compositeAccount,
            }
        }
    }

    /// Instruction data for ProcessRustTypes
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ProcessRustTypesInstructionData {
        pub inputU8: u8,

        pub inputU16: u16,

        pub inputU32: u32,

        pub inputU64: u64,

        pub inputI8: i8,

        pub inputI16: i16,

        pub inputI32: i32,

        pub inputI64: i64,

        pub inputI128: i128,

        pub inputF32: f32,

        pub inputF64: f64,

        pub inputString: String,

        pub inputVec: Vec<u8>,

        pub inputVecString: Vec<String>,

        pub inputBool: bool,
    }

    impl ProcessRustTypesInstructionData {
        pub fn new(
            inputU8: u8,

            inputU16: u16,

            inputU32: u32,

            inputU64: u64,

            inputI8: i8,

            inputI16: i16,

            inputI32: i32,

            inputI64: i64,

            inputI128: i128,

            inputF32: f32,

            inputF64: f64,

            inputString: String,

            inputVec: Vec<u8>,

            inputVecString: Vec<String>,

            inputBool: bool,
        ) -> Self {
            Self {
                inputU8,

                inputU16,

                inputU32,

                inputU64,

                inputI8,

                inputI16,

                inputI32,

                inputI64,

                inputI128,

                inputF32,

                inputF64,

                inputString,

                inputVec,

                inputVecString,

                inputBool,
            }
        }
    }

    /// Implementation for ProcessRustTypesInstruction
    impl ProcessRustTypesInstruction {
        fn discriminator() -> [u8; 8] {
            [74u8, 102u8, 18u8, 245u8, 253u8, 10u8, 252u8, 246u8]
        }

        pub fn data(data: ProcessRustTypesInstructionData) -> Self {
            Self {
                accounts: ProcessRustTypesInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ProcessRustTypesInstructionAccounts) -> Self {
            self.accounts
                .compositeAccountNested
                .set_from_accounts(accounts.compositeAccountNested);

            self.accounts.signer = AccountMeta::new(accounts.signer, true);

            self.accounts.dataAccount1 = AccountMeta::new_readonly(accounts.dataAccount1, false);

            self.accounts.dataAccount2 = AccountMeta::new_readonly(accounts.dataAccount2, false);

            self.accounts.dataAccount3 = AccountMeta::new_readonly(accounts.dataAccount3, false);

            self.accounts.dataAccount4 = AccountMeta::new_readonly(accounts.dataAccount4, false);

            self.accounts.dataAccount5 = AccountMeta::new_readonly(accounts.dataAccount5, false);

            self.accounts.dataAccount6 = AccountMeta::new_readonly(accounts.dataAccount6, false);

            self.accounts
                .compositeAccount
                .set_from_accounts(accounts.compositeAccount);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.extend(self.accounts.compositeAccountNested.to_account_metas());

            metas.push(self.accounts.signer.clone());

            metas.push(self.accounts.dataAccount1.clone());

            metas.push(self.accounts.dataAccount2.clone());

            metas.push(self.accounts.dataAccount3.clone());

            metas.push(self.accounts.dataAccount4.clone());

            metas.push(self.accounts.dataAccount5.clone());

            metas.push(self.accounts.dataAccount6.clone());

            metas.extend(self.accounts.compositeAccount.to_account_metas());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ProcessCustomTypes
    // ....................................................................

    /// Main instruction struct for ProcessCustomTypes
    pub struct ProcessCustomTypesInstruction {
        pub accounts: ProcessCustomTypesInstructionAccountMetas,
        pub data: ProcessCustomTypesInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ProcessCustomTypes instruction
    #[derive(Debug, Clone, Default)]
    pub struct ProcessCustomTypesInstructionAccountMetas {
        pub compositeAccountNested: CompositeAccountNestedInstructionAccountMetas,

        pub signer: AccountMeta,

        pub dataAccount1: AccountMeta,

        pub dataAccount2: AccountMeta,

        pub dataAccount3: AccountMeta,

        pub dataAccount4: AccountMeta,

        pub dataAccount5: AccountMeta,

        pub dataAccount6: AccountMeta,

        pub compositeAccount: CompositeAccountInstructionAccountMetas,
    }

    /// Account pubkeys for ProcessCustomTypes instruction
    #[derive(Debug, Clone)]
    pub struct ProcessCustomTypesInstructionAccounts {
        pub compositeAccountNested: CompositeAccountNestedInstructionAccounts,

        pub signer: Pubkey,

        pub dataAccount1: Pubkey,

        pub dataAccount2: Pubkey,

        pub dataAccount3: Pubkey,

        pub dataAccount4: Pubkey,

        pub dataAccount5: Pubkey,

        pub dataAccount6: Pubkey,

        pub compositeAccount: CompositeAccountInstructionAccounts,
    }

    impl ProcessCustomTypesInstructionAccounts {
        pub fn new(
            compositeAccountNested: CompositeAccountNestedInstructionAccounts,

            signer: Pubkey,

            dataAccount1: Pubkey,

            dataAccount2: Pubkey,

            dataAccount3: Pubkey,

            dataAccount4: Pubkey,

            dataAccount5: Pubkey,

            dataAccount6: Pubkey,

            compositeAccount: CompositeAccountInstructionAccounts,
        ) -> Self {
            Self {
                compositeAccountNested,

                signer,

                dataAccount1,

                dataAccount2,

                dataAccount3,

                dataAccount4,

                dataAccount5,

                dataAccount6,

                compositeAccount,
            }
        }
    }

    /// Instruction data for ProcessCustomTypes
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ProcessCustomTypesInstructionData {
        pub inputClassic: ClassicStruct,

        pub inputOptional: OptionalFields,

        pub inputTuple: TupleStruct,

        pub inputEnum: SimpleEnum,

        pub inputDataEnum: DataEnum,

        pub inputMultiDataEnum: MultiDataEnum,

        pub inputNamedFieldsEnum: NamedFieldsEnum,

        pub inputGenericEnum: UnknownType,

        pub inputUnitVariants: UnitVariants,

        pub inputNested: NestedStruct,

        pub inputDefault: DefaultStruct,

        pub inputGenericStruct: UnknownType,
    }

    impl ProcessCustomTypesInstructionData {
        pub fn new(
            inputClassic: ClassicStruct,

            inputOptional: OptionalFields,

            inputTuple: TupleStruct,

            inputEnum: SimpleEnum,

            inputDataEnum: DataEnum,

            inputMultiDataEnum: MultiDataEnum,

            inputNamedFieldsEnum: NamedFieldsEnum,

            inputGenericEnum: UnknownType,

            inputUnitVariants: UnitVariants,

            inputNested: NestedStruct,

            inputDefault: DefaultStruct,

            inputGenericStruct: UnknownType,
        ) -> Self {
            Self {
                inputClassic,

                inputOptional,

                inputTuple,

                inputEnum,

                inputDataEnum,

                inputMultiDataEnum,

                inputNamedFieldsEnum,

                inputGenericEnum,

                inputUnitVariants,

                inputNested,

                inputDefault,

                inputGenericStruct,
            }
        }
    }

    /// Implementation for ProcessCustomTypesInstruction
    impl ProcessCustomTypesInstruction {
        fn discriminator() -> [u8; 8] {
            [37u8, 23u8, 242u8, 88u8, 134u8, 197u8, 190u8, 108u8]
        }

        pub fn data(data: ProcessCustomTypesInstructionData) -> Self {
            Self {
                accounts: ProcessCustomTypesInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ProcessCustomTypesInstructionAccounts) -> Self {
            self.accounts
                .compositeAccountNested
                .set_from_accounts(accounts.compositeAccountNested);

            self.accounts.signer = AccountMeta::new(accounts.signer, true);

            self.accounts.dataAccount1 = AccountMeta::new_readonly(accounts.dataAccount1, false);

            self.accounts.dataAccount2 = AccountMeta::new_readonly(accounts.dataAccount2, false);

            self.accounts.dataAccount3 = AccountMeta::new_readonly(accounts.dataAccount3, false);

            self.accounts.dataAccount4 = AccountMeta::new_readonly(accounts.dataAccount4, false);

            self.accounts.dataAccount5 = AccountMeta::new_readonly(accounts.dataAccount5, false);

            self.accounts.dataAccount6 = AccountMeta::new_readonly(accounts.dataAccount6, false);

            self.accounts
                .compositeAccount
                .set_from_accounts(accounts.compositeAccount);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.extend(self.accounts.compositeAccountNested.to_account_metas());

            metas.push(self.accounts.signer.clone());

            metas.push(self.accounts.dataAccount1.clone());

            metas.push(self.accounts.dataAccount2.clone());

            metas.push(self.accounts.dataAccount3.clone());

            metas.push(self.accounts.dataAccount4.clone());

            metas.push(self.accounts.dataAccount5.clone());

            metas.push(self.accounts.dataAccount6.clone());

            metas.extend(self.accounts.compositeAccount.to_account_metas());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Data Accounts (with discriminators)
    // ------------------------------------------------------------------------

    /// AccountDiscriminator implementation for ClassicStructAccount
    impl AccountDiscriminator for ClassicStructAccount {
        fn discriminator() -> &'static [u8] {
            &[0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8]
        }
    }

    /// AccountDiscriminator implementation for DataAccount
    impl AccountDiscriminator for DataAccount {
        fn discriminator() -> &'static [u8] {
            &[0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8]
        }
    }

    /// AccountDiscriminator implementation for NestedStructAccount
    impl AccountDiscriminator for NestedStructAccount {
        fn discriminator() -> &'static [u8] {
            &[0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8]
        }
    }

    /// AccountDiscriminator implementation for OptionalFieldsAccount
    impl AccountDiscriminator for OptionalFieldsAccount {
        fn discriminator() -> &'static [u8] {
            &[0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8, 0u8]
        }
    }

    // ------------------------------------------------------------------------
    // Errors
    // ------------------------------------------------------------------------

    /// Program errors for idl_test
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    #[repr(u32)]
    pub enum IdltestError {
        /// The input is too long
        InputTooLong = 6000,

        /// The input is too short
        InputTooShort = 6001,

        /// The input is invalid
        InvalidInput = 6002,

        /// The input is too big
        InputTooBig = 6003,

        /// The input is too small
        InputTooSmall = 6004,
    }

    impl IdltestError {
        /// Get the error code
        pub fn code(&self) -> u32 {
            *self as u32
        }

        /// Get the error message
        pub fn msg(&self) -> &'static str {
            match self {
                Self::InputTooLong => "The input is too long",

                Self::InputTooShort => "The input is too short",

                Self::InvalidInput => "The input is invalid",

                Self::InputTooBig => "The input is too big",

                Self::InputTooSmall => "The input is too small",
            }
        }

        /// Try to convert from error code
        pub fn from_code(code: u32) -> Option<Self> {
            match code {
                6000 => Some(Self::InputTooLong),

                6001 => Some(Self::InputTooShort),

                6002 => Some(Self::InvalidInput),

                6003 => Some(Self::InputTooBig),

                6004 => Some(Self::InputTooSmall),

                _ => None,
            }
        }
    }

    impl std::fmt::Display for IdltestError {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{}: {}", self.code(), self.msg())
        }
    }

    impl std::error::Error for IdltestError {}

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------

    /// Composite Account: compositeAccountNested
    #[derive(Debug, Clone, Default)]
    pub struct CompositeAccountNestedInstructionAccountMetas {
        pub someAccount: AccountMeta,

        pub nestedInner: NestedInnerInstructionAccountMetas,
    }

    impl CompositeAccountNestedInstructionAccountMetas {
        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.someAccount.clone());

            metas.extend(self.nestedInner.to_account_metas());

            metas
        }

        fn set_from_accounts(&mut self, accounts: CompositeAccountNestedInstructionAccounts) {
            self.someAccount = AccountMeta::new(accounts.someAccount, false);

            self.nestedInner.set_from_accounts(accounts.nestedInner);
        }
    }

    #[derive(Debug, Clone)]
    pub struct CompositeAccountNestedInstructionAccounts {
        pub someAccount: Pubkey,

        pub nestedInner: NestedInnerInstructionAccounts,
    }

    impl CompositeAccountNestedInstructionAccounts {
        pub fn new(someAccount: Pubkey, nestedInner: NestedInnerInstructionAccounts) -> Self {
            Self {
                someAccount,

                nestedInner,
            }
        }
    }

    #[derive(Debug, Clone, Default)]
    pub struct NestedInnerInstructionAccountMetas {
        pub someAccount: AccountMeta,

        pub systemProgram: AccountMeta,

        pub deployer: AccountMeta,
    }

    impl NestedInnerInstructionAccountMetas {
        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.someAccount.clone());

            metas.push(self.systemProgram.clone());

            metas.push(self.deployer.clone());

            metas
        }

        fn set_from_accounts(&mut self, accounts: NestedInnerInstructionAccounts) {
            self.someAccount = AccountMeta::new_readonly(accounts.someAccount, false);

            self.systemProgram = AccountMeta::new_readonly(accounts.systemProgram, false);

            self.deployer = AccountMeta::new(accounts.deployer, true);
        }
    }

    #[derive(Debug, Clone)]
    pub struct NestedInnerInstructionAccounts {
        pub someAccount: Pubkey,

        pub systemProgram: Pubkey,

        pub deployer: Pubkey,
    }

    impl NestedInnerInstructionAccounts {
        pub fn new(someAccount: Pubkey, systemProgram: Pubkey, deployer: Pubkey) -> Self {
            Self {
                someAccount,

                systemProgram,

                deployer,
            }
        }
    }

    /// Composite Account: compositeAccount
    #[derive(Debug, Clone, Default)]
    pub struct CompositeAccountInstructionAccountMetas {
        pub someAccount: AccountMeta,

        pub signer: AccountMeta,

        pub dataAccount1: AccountMeta,
    }

    impl CompositeAccountInstructionAccountMetas {
        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.someAccount.clone());

            metas.push(self.signer.clone());

            metas.push(self.dataAccount1.clone());

            metas
        }

        fn set_from_accounts(&mut self, accounts: CompositeAccountInstructionAccounts) {
            self.someAccount = AccountMeta::new_readonly(accounts.someAccount, false);

            self.signer = AccountMeta::new(accounts.signer, true);

            self.dataAccount1 = AccountMeta::new_readonly(accounts.dataAccount1, false);
        }
    }

    #[derive(Debug, Clone)]
    pub struct CompositeAccountInstructionAccounts {
        pub someAccount: Pubkey,

        pub signer: Pubkey,

        pub dataAccount1: Pubkey,
    }

    impl CompositeAccountInstructionAccounts {
        pub fn new(someAccount: Pubkey, signer: Pubkey, dataAccount1: Pubkey) -> Self {
            Self {
                someAccount,

                signer,

                dataAccount1,
            }
        }
    }

    // ------------------------------------------------------------------------
    // Custom Types
    // ------------------------------------------------------------------------

    /// Custom struct: ClassicStructAccount
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ClassicStructAccount {
        pub field1: u8,

        pub field2: u16,

        pub field3: Pubkey,
    }

    impl ClassicStructAccount {
        pub fn new(field1: u8, field2: u16, field3: Pubkey) -> Self {
            Self {
                field1,

                field2,

                field3,
            }
        }
    }

    /// Custom struct: ClassicStruct
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ClassicStruct {
        pub field1: u8,

        pub field2: u16,

        pub field3: Pubkey,
    }

    impl ClassicStruct {
        pub fn new(field1: u8, field2: u16, field3: Pubkey) -> Self {
            Self {
                field1,

                field2,

                field3,
            }
        }
    }

    /// Custom enum: DataEnum
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub enum DataEnum {
        Integer(i32),

        Float(f64),

        Text(String),

        Pubkey(Pubkey),
    }

    /// Custom struct: DefaultStruct
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct DefaultStruct {
        pub field1: u8,

        pub field2: u16,

        pub field3: Pubkey,
    }

    impl DefaultStruct {
        pub fn new(field1: u8, field2: u16, field3: Pubkey) -> Self {
            Self {
                field1,

                field2,

                field3,
            }
        }
    }

    /// Custom enum: GenericEnum
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub enum GenericEnum {
        Value(T),

        None,
    }

    /// Custom struct: GenericStruct
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct GenericStruct {
        pub value: T,

        pub key: Pubkey,
    }

    impl GenericStruct {
        pub fn new(value: T, key: Pubkey) -> Self {
            Self { value, key }
        }
    }

    /// Custom enum: MultiDataEnum
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub enum MultiDataEnum {
        Pair(i32, i32),

        Triple(i32, i32, i32),

        Pubkey(Pubkey, Pubkey),
    }

    /// Custom enum: NamedFieldsEnum
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub enum NamedFieldsEnum {
        Point { x: f64, y: f64 },

        Circle { radius: f64 },

        Pubkey { pubkey1: Pubkey, pubkey2: Pubkey },
    }

    /// Custom struct: NestedStruct
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct NestedStruct {
        pub inner: ClassicStruct,

        pub key: Pubkey,
    }

    impl NestedStruct {
        pub fn new(inner: ClassicStruct, key: Pubkey) -> Self {
            Self { inner, key }
        }
    }

    /// Custom struct: OptionalFields
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct OptionalFields {
        pub field1: Option<u8>,

        pub field2: Option<u16>,

        pub field3: Option<Pubkey>,
    }

    impl OptionalFields {
        pub fn new(field1: Option<u8>, field2: Option<u16>, field3: Option<Pubkey>) -> Self {
            Self {
                field1,

                field2,

                field3,
            }
        }
    }

    /// Custom enum: SimpleEnum
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub enum SimpleEnum {
        Variant1,

        Variant2,

        Pubkey,
    }

    /// Custom enum: UnitVariants
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub enum UnitVariants {
        VariantA,

        VariantB,

        VariantC,
    }

    /// Custom struct: DataAccount
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct DataAccount {
        pub unitStruct: UnitStruct,

        pub tupleStruct: TupleStruct,

        pub classicStruct: ClassicStruct,

        pub genericStruct: UnknownType,

        pub optionalFields: OptionalFields,

        pub defaultStruct: DefaultStruct,

        pub nestedStruct: NestedStruct,

        pub simpleEnum: SimpleEnum,

        pub dataEnum: DataEnum,

        pub multiDataEnum: MultiDataEnum,

        pub namedFieldsEnum: NamedFieldsEnum,

        pub genericEnum: UnknownType,

        pub unitVariants: UnitVariants,
    }

    impl DataAccount {
        pub fn new(
            unitStruct: UnitStruct,

            tupleStruct: TupleStruct,

            classicStruct: ClassicStruct,

            genericStruct: UnknownType,

            optionalFields: OptionalFields,

            defaultStruct: DefaultStruct,

            nestedStruct: NestedStruct,

            simpleEnum: SimpleEnum,

            dataEnum: DataEnum,

            multiDataEnum: MultiDataEnum,

            namedFieldsEnum: NamedFieldsEnum,

            genericEnum: UnknownType,

            unitVariants: UnitVariants,
        ) -> Self {
            Self {
                unitStruct,

                tupleStruct,

                classicStruct,

                genericStruct,

                optionalFields,

                defaultStruct,

                nestedStruct,

                simpleEnum,

                dataEnum,

                multiDataEnum,

                namedFieldsEnum,

                genericEnum,

                unitVariants,
            }
        }
    }

    /// Custom struct: NestedStructAccount
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct NestedStructAccount {
        pub inner: ClassicStructAccount,
    }

    impl NestedStructAccount {
        pub fn new(inner: ClassicStructAccount) -> Self {
            Self { inner }
        }
    }

    /// Custom struct: OptionalFieldsAccount
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct OptionalFieldsAccount {
        pub field1: Option<u8>,

        pub field2: Option<u16>,

        pub field3: Option<Pubkey>,
    }

    impl OptionalFieldsAccount {
        pub fn new(field1: Option<u8>, field2: Option<u16>, field3: Option<Pubkey>) -> Self {
            Self {
                field1,

                field2,

                field3,
            }
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
