[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
unauthorized_access_2 = "5XvBmfPNcHLCgbRK4nRYvfodAnhjArHSed2B3rhkF1Ug"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/andrej/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
