[config]
default_to_workspace = false
min_version = "0.32.15"

[config.modify_core_tasks]
private = true
namespace = "default"

[tasks.trident]
description = "Run Trident CLI"
command = "cargo"
args = ["run", "--manifest-path", "../../crates/cli/Cargo.toml", "--", "${@}"]
