name: "Setup Solana"

runs:
  using: "composite"
  steps:
    # Cache the Solana CLI
    - name: Cache Solana CLI
      uses: actions/cache@v4
      with:
        path: ~/.local/share/solana/install/active_release
        key: ${{ runner.os }}-solana-${{ env.SOLANA_VERSION }}

    # Install Solana CLI
    - name: Install Solana CLI
      run: |
        sh -c "$(curl -sSfL https://release.anza.xyz/v${{ env.SOLANA_VERSION }}/install)"
      shell: bash

    # Set Solana Path variables
    - name: Set Solana Path variables
      run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      shell: bash
