[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
arbitrary_custom_types_4 = "CdWkp3CY9CAjBQP73SDCwDDfsumwY7e6DDSjrN5u8Cii"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/andrej/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
