name: "Setup Python"
description: "Setup Python for documentation with necessary libraries"

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r documentation/requirements.txt
      shell: bash
