[package]
name = "callee"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "callee"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]
trident-fuzzing = ["dep:trident-fuzz"]

[dependencies]
anchor-lang = "0.30.1"

[dependencies.trident-derive-accounts-snapshots]
path = "../../../../../crates/fuzz/derive/accounts_snapshots"

[dependencies.trident-fuzz]
path = "../../../../../crates/fuzz"
optional = true
