[package]
name = "arbitrary-limit-inputs-5"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "arbitrary_limit_inputs_5"

[features]
default = ["trident-fuzzing"]
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
trident-fuzzing = ["trident-client"]

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
trident-client = { path = "../../../../../crates/client", optional = true }
