[[bin]]
name = "fuzz_0"
path = "fuzz_0/test_fuzz.rs"

[package]
name = "fuzz_tests"
version = "0.1.0"
description = "Created with Trident"
edition = "2021"

[dependencies]
arbitrary = "1.3.0"
borsh = "1.5.3"
anchor-spl = { git = "https://github.com/coral-xyz/anchor", branch = "master" }
anchor-lang = { git = "https://github.com/coral-xyz/anchor", branch = "master" }


[dependencies.trident-fuzz]
path = "../../../../crates/fuzz"
