//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;
use trident_fuzz::AccountDiscriminator;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: fork
// ----------------------------------------------------------------------------
pub mod fork {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for fork
    pub fn program_id() -> Pubkey {
        pubkey!("9nGj2iwXYhaQktGxiJgJ5aGBhfSb5ubYXxc1bZy4MD2k")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: Initialize
    // ....................................................................

    /// Main instruction struct for Initialize
    pub struct InitializeInstruction {
        pub accounts: InitializeInstructionAccountMetas,
        pub data: InitializeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Initialize instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeInstructionAccountMetas {
        pub sender_wallet: AccountMeta,

        pub receiver_wallet: AccountMeta,

        pub wrapped_sol: AccountMeta,

        pub metadao: AccountMeta,

        pub kamino_lending: AccountMeta,

        pub jupiter_aggregator_v6: AccountMeta,

        pub marinade_bond: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for Initialize instruction
    #[derive(Debug, Clone)]
    pub struct InitializeInstructionAccounts {
        pub sender_wallet: Pubkey,

        pub receiver_wallet: Pubkey,
    }

    impl InitializeInstructionAccounts {
        pub fn new(sender_wallet: Pubkey, receiver_wallet: Pubkey) -> Self {
            Self {
                sender_wallet,

                receiver_wallet,
            }
        }
    }

    /// Instruction data for Initialize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeInstructionData {}

    impl InitializeInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for InitializeInstruction
    impl InitializeInstruction {
        fn discriminator() -> [u8; 8] {
            [175u8, 175u8, 109u8, 31u8, 13u8, 152u8, 155u8, 237u8]
        }

        pub fn data(data: InitializeInstructionData) -> Self {
            Self {
                accounts: InitializeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeInstructionAccounts) -> Self {
            self.accounts.sender_wallet = AccountMeta::new(accounts.sender_wallet, true);

            self.accounts.receiver_wallet = AccountMeta::new(accounts.receiver_wallet, false);

            self.accounts.wrapped_sol = AccountMeta::new_readonly(
                pubkey!("So11111111111111111111111111111111111111112"),
                false,
            );

            self.accounts.metadao = AccountMeta::new_readonly(
                pubkey!("moontUzsdepotRGe5xsfip7vLPTJnVuafqdUWexVnPM"),
                false,
            );

            self.accounts.kamino_lending = AccountMeta::new_readonly(
                pubkey!("KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD"),
                false,
            );

            self.accounts.jupiter_aggregator_v6 = AccountMeta::new_readonly(
                pubkey!("JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4"),
                false,
            );

            self.accounts.marinade_bond = AccountMeta::new_readonly(
                pubkey!("vBoNdEvzMrSai7is21XgVYik65mqtaKXuSdMBJ1xkW4"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.sender_wallet.clone());

            metas.push(self.accounts.receiver_wallet.clone());

            metas.push(self.accounts.wrapped_sol.clone());

            metas.push(self.accounts.metadao.clone());

            metas.push(self.accounts.kamino_lending.clone());

            metas.push(self.accounts.jupiter_aggregator_v6.clone());

            metas.push(self.accounts.marinade_bond.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Data Accounts (with discriminators)
    // ------------------------------------------------------------------------

    // ------------------------------------------------------------------------
    // Errors
    // ------------------------------------------------------------------------

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------

    // ------------------------------------------------------------------------
    // Custom Types
    // ------------------------------------------------------------------------
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
