# For the detailed description of the parameters, see: https://ackee.xyz/trident/docs/latest/features/trident-manifest/

[fuzz]
fuzzing_with_stats = true

[honggfuzz]
iterations = 10000
run_time = 20
exit_upon_crash = true

[afl]
iterations = 10000
run_time = 20
