# For the detailed description of the parameters, see: https://ackee.xyz/trident/docs/latest/features/trident-manifest/

[fuzz.metrics]
enabled = true
json = true
dashboard=true


[fuzz.coverage]
enable = true
loopcount = 5
format = "json"
attach_extension = true