[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
unchecked_arithmetic_0 = "BM8vocQeC2VuDf1KhbHLsZxTh7owzDNTAkKyZoTxFiUs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/andrej/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
