[config]
default_to_workspace = false
min_version = "0.32.15"

[config.modify_core_tasks]
private = true
namespace = "default"

[tasks.trdelnik]
description = "Run Trdelnik CLI"
command = "cargo"
args = ["run", "--manifest-path", "../../crates/trdelnik_cli/Cargo.toml", "--", "${@}"]
