name: Build documentation

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.DOCUMENTATION_DEPLOY_KEY }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: ./.github/actions/setup-documentation/
      - name: Fetch documentation branch
        run: git fetch origin documentation:documentation --depth=1
      - name: Build documentation
        working-directory: ./documentation
        run: |
          git config --global user.email "trident@ackee.xyz"
          git config --global user.name "Trident bot"
          mike deploy -b documentation dev
      - name: Checkout documentation branch
        run: git checkout -f documentation
      - name: Push documentation
        uses: ad-m/github-push-action@master
        with:
          ssh: true
          branch: documentation
