name: Purge latest docs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  purge-latest-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Purge latest docs
        run: ./purge_cache.sh
        env:
          DOMAIN_ZONE_ID: ${{ secrets.DOMAIN_ZONE_ID }}
          DOMAIN_TOKEN: ${{ secrets.DOMAIN_TOKEN }}
