name: "Setup Honggfuzz"

runs:
  using: "composite"
  steps:
    # Install system dependencies required by Honggfuzz
    - name: Install Dependencies (binutils-dev & libunwind-dev)
      run: |
        sudo apt-get update  # Update the system package lists
        sudo apt-get install -y binutils-dev libunwind-dev  # Install binutils-dev and libunwind-dev, which are required for fuzzing
      shell: bash

    # Install Honggfuzz using Cargo
    - name: Install Honggfuzz
      run: cargo install honggfuzz --version ${{ env.HONGGFUZZ_VERSION }}  # Install the specified version of Honggfuzz via Cargo
      shell: bash
